### ISSUE TITLE
Mobile functions

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [foxingcreative/cliff-michaels#184]
when a user logs in to their account on mobile, they can't see the "access course" button but if they click the title or image it will go t the course. Is there any way to ever get mobile experience to show a button or same word that the laptop user sees (i.e.: "preview" on home page or "access course" in te account page -- this is particularly important when I hit asia / india -- everyone lives on mobile -- many can't afford laptops. But even in US, mobile is what 14-34 year olds live on - they don't even want to be on their laptops anymore

**Comment by sethrubenstein** [comment]
Right everyone lives on mobile. Theyve been trained through user interaction to click on photos, ie the thumbnails to reach things. Thats a normal UX pattern. I can add Access Course button in but thatd be a precious waste of space on mobile. Why dont you try it out with your demographic there for 14-34 yr olds and see if they have any trouble before we make a change.

**Comment by cliffmichaelsgithub** [comment]
Ok - we'll table that issue :)
